### ISSUE TITLE
Sharpening Kits bypass stages

### ISSUE THREAD

**Issue by Thyriel** [Darkhax-Minecraft/TinkerStages#4]
As title. With Tinker's sharpening kits it's possible to bypass restriction set with TinkerStages.
For example i locked copper to a certain stage. When i cheat a copper pickaxe it gets instantly dropped and i can't assemble one in the tool station, but as i can use copper in the smeltery (which is fine) i can craft a copper sharpening kit and use it (with flint) in tool station to get a "copper equivalent" upgraded pickaxe.

Would be great, similar to parts being of a locked material can't be used in the tool forge/station, when sharpening kits of those materials get locked too from being used.

**Comment by Darkhax** [comment]
Thank you for the report. I will look into a solution.

**Comment by Thyriel** [comment]
Found a way until you fixed it to bypass that problem:
ModTweaker readded TiC support recently, so running a script with that code prevents players from being able to make sharpening kits:
`mods.tconstruct.Casting.removeTableRecipe(<tconstruct:sharpening_kit>);`

**Comment by Thyriel** [comment]
Just realized the problem is not only by sharpening kits but almost all materials that can be used to upgrade a tool. For example adding an emerald (which is easily obtainable via villager trading) increases every tool to diamond level too.

Imho a great solution would be if you could do it so that when a material is locked through a stage that it can't be used as upgrade (modifier) too

**Comment by Darkhax** [comment]
Thanks for the further information. I will try to get this one worked out today.

**Comment by royalcw** [comment]
Is there a way to prevent the smeltery from even casting staged materials?  I'm testing this mod and using copper as my restriction until a player unlocks the Copper Age.  In my mind, this means that the casting of parts shouldn't work until the stage requirements is met.  That'll prevent people from casting the parts or sharpening stones unless the stage is met too.  Maybe a comment pops up in chat saying, "you have not met the casting requirements for this material yet".

**Comment by Darkhax** [comment]
@royalcw You should make your own issue for this instead of getting an unrelated issue off topic. To answer your question though, Tinkers Construct does not support player-specific casting recipes, meaning this is not possible. I have talked with the tcon devs about trying to implement this feature however the way the smeltery is designed, it's just not possible. There are other mods that you can use such as [RecipeStages](https://minecraft.curseforge.com/projects/recipe-stages) to make recipes using the item be restricted until the stage is unlocked. And [ItemStages](https://minecraft.curseforge.com/projects/item-stages) to restrict the item from being held/used or seen in JEI.

**Comment by Darkhax** [comment]
After talking with the devs of tcon and further consideration, I think the best thing to do is disable sharpening kits or ensure that the materials are not available until a later stage. ItemStages can also be used as a fallback to prevent them if you must have them in your pack.
